# Generated by Django 5.1.2 on 2024-10-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField(verbose_name='User Message ')),
                ('bot_response', models.TextField(blank=True, verbose_name='Bot Answer')),
            ],
        ),
    ]
